baseURL = "https://bigsmooth68.github.io/"
name = "bigsmooth68.github.io"
title = "bigsmooth68.github.io"
theme = "paper"
paginate = 7
languageCode = "en"
DefaultContentLanguage = "en"

[params]
  github = 'bigsmooth68'
  linkedin = 'olivierspiesser'
  name = 'Olivier Spiesser'
  author = "Olivier Spiesser"
  bio = 'My blogs posted on dbi services blogs site'
  description = 'Blog technique â€” monitoring, Zabbix, Ansible, Kafka et plus.'
  color = 'light'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[markup.goldmark.renderer]
unsafe = true

[services]
  [services.googleAnalytics]
    ID = 'G-MHWFFCJS0T'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

# config.toml

# Enable taxonomies
[taxonomies]
  tag = "tags"

# URL structure for taxonomy term pages
[permalinkBaseName]
  tag = "/tags"
